apiVersion: v1
kind: Service
metadata:
  name: zipkin-service
  labels:
    app: zipkin-service
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 9411
      nodePort: 30011
  type: NodePort
  selector:
    app: zipkin-deployment
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: zipkin-service
  labels:
    account: zipkin-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin-deployment
  labels:
    app: zipkin-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zipkin-deployment
  template:
    metadata:
      labels:
        app: zipkin-deployment
    spec:
      serviceAccountName: zipkin-service
      containers:
        - name: zipkin-deployment
          image: openzipkin/zipkin
          imagePullPolicy: IfNotPresent
          readinessProbe:
            httpGet:
              path: "/api/v2/services"
              port: 9411
            initialDelaySeconds: 5
          resources:
            limits:
              memory: "500Mi"
              cpu: "500m"
            requests:
              memory: "200Mi"
              cpu: "200m"
          securityContext:
            runAsUser: 1000
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 9411
              name: http
              protocol: TCP
