apiVersion: v1
kind: Service
metadata:
  name: payment-service
  labels:
    app: payment-service
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  type: LoadBalancer
  selector:
    app: payment-deployment
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: payment-service
  labels:
    account: payment-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment-v1
  labels:
    app: payment-deployment
    version: 1.1.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-deployment
      version: 1.1.0
  template:
    metadata:
      labels:
        app: payment-deployment
        version: 1.1.0
    spec:
      serviceAccountName: payment-service
      containers:
        - name: payment-deployment-v1
          image: ashutoshsahoo/payment-service
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "500Mi"
              cpu: "500m"
            requests:
              memory: "200Mi"
              cpu: "200m"
          securityContext:
            runAsUser: 1000
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
            - name: SPRING_KAFKA_BOOTSTRAP-SERVERS
              value: http://my-kafka-cp-kafka:9092
            - name: SPRING_KAFKA_PROPERTIES_SCHEMA_REGISTRY_URL
              value: http://my-kafka-cp-schema-registry:8081
            - name: SPRING_ZIPKIN_BASE-URL
              value: zipkin-service
