spring:
  application:
    name: order-service
  main:
    banner-mode: off
  zipkin:
    base-url: http://localhost:9411/
  kafka:
    bootstrap-servers: http://localhost:9092
    producer:
      key-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    properties:
      schema.registry.url: http://localhost:8081
      specific.avro.reader: true

    streams:
      properties:
        default.key.serde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
        default.value.serde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
      state-dir: /tmp/kafka-streams/2

logging:
  level:
    root: warn
    com.ashu.practice: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"